### ISSUE TITLE
画像ファイルにSVGを使うとエラーになる

### ISSUE THREAD

**Issue by acliss19xx** [concrete5japan/Manual-Nav#14]
2016-05-13 現在 また確認していませんがSVGを使うとエラーになるという報告をいただいています
https://www.concrete5.org/marketplace/addons/manual-nav1/support/svg/

**Comment by tao-s** [comment]
SVG自体がconcrete5のファイルマネージャーでエラーになります。
サムネイルの生成でコケるんですよ

**Comment by acliss19xx** [comment]
拡張子がsvgの時は、imgタグで出力すればいけますか？

**Comment by acliss19xx** [comment]
f42af9e
