### ISSUE TITLE
Support c5's external link / 外部リンク対応

### ISSUE THREAD

**Issue by katzueno** [concrete5japan/Manual-Nav#17]
Manual Nav block doesn't support concrete5's external link function yet.
You can fix it by taking a look at Page List's block's default view.php

concrete5 の「外部リンク」ページの対応がされていない。
ページリストブロックの、標準の view.php に対応策が書いてあります。

**Comment by katzueno** [comment]
@acliss19xx さん、マーケットプレイスの商品をアップデートして掲載していただけますか？

**Comment by hissy** [comment]
Already fixed, should close this issue
