### ISSUE TITLE
Word 'Entry' should be 'Link'

### ISSUE THREAD

**Issue by Mesuva** [concrete5japan/Manual-Nav#4]
Instead of 'Add Entry' and 'Delete Entry', it should be 'Add Link' and 'Delete Link'.

The word 'Entry' means a large piece of data, e.g.  'an entry in a blog'

**Comment by katzueno** [comment]
Thanks! We'll make a change or you can send us a PR

**Comment by Mesuva** [comment]
I think quicker for you to make the change instead of me doing a pull request.

Great work, all worked fine from my testing

**Comment by katzueno** [comment]
@Mesuva

Thanks!

I know it's quicker to fix on our end for this kind of fix.

You could get the credit by sending us a PR.

Next time, you can just go ahead and send us a PR!
