### ISSUE TITLE
No borders on inputs make the fields invisible 

### ISSUE THREAD

**Issue by nickratering** [concrete5japan/Manual-Nav#40]
No borders on inputs make the fields invisible and not to understand for some clients.
Maybe a class 'form-control' on the input fields will improve this.

<img width="680" alt="Screenshot 2023-10-10 at 21 57 27" src="https://github.com/concrete5japan/Manual-Nav/assets/3337142/85d4adc6-3e5a-487f-95e1-5539c5eeba43">
<img width="694" alt="Screenshot 2023-10-10 at 21 57 05" src="https://github.com/concrete5japan/Manual-Nav/assets/3337142/60023dd0-5023-4711-a790-2c8bc3c45fd7">

**Comment by biplobice** [comment]
Fixed in v3.0.1
