### ISSUE TITLE
マニュアルナビに画像を選べる様にして欲しいです。

### ISSUE THREAD

**Issue by djkazu** [concrete5japan/Manual-Nav#6]
マニュアルナビを使う際に画像＆テキストができたら、使える幅が広がると思い書き込みをしました。
実際、私自身がそう使いたいという要望もあります。
バージョンアップしていただけないでしょうか。
よろしくお願いいたします。

**Comment by acliss19xx** [comment]
画像を使ったナビをしたいのであれば、画像スライダーのカスタムテンプレートでも作れます。
また、画像を使う場合「ページ属性を使う」「ブロックの編集で画像を追加」などの設定方法がありますが、具体的にどのような設定方法を考えられていますか？

**Comment by djkazu** [comment]
お願いをしていて申し訳ありません。
ソーシャルナビで対応できました。

**Comment by acliss19xx** [comment]
はい、了解です。バージョン１系はこのまま残して、2系を作っていきます。ページリストのように、ページ属性のthumbnailを使うパターンと画像を選択できるパターンを作りたいと思います。時間下さい。

**Comment by acliss19xx** [comment]
issue #8  でやるのでクローズします。
